CREATE TYPE "AiAnalysisStatus" AS ENUM ('NOT_REQUESTED', 'PLANNED', 'COMPLETED', 'UNAVAILABLE');

ALTER TABLE "QaRun"
ADD COLUMN "aiProvider" TEXT,
ADD COLUMN "aiModel" TEXT,
ADD COLUMN "aiAnalysisStatus" "AiAnalysisStatus" NOT NULL DEFAULT 'NOT_REQUESTED',
ADD COLUMN "aiTestPlan" JSONB,
ADD COLUMN "aiAnalysis" JSONB;
