ALTER TYPE "AiAnalysisStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "AiAnalysisStatus" ADD VALUE IF NOT EXISTS 'RUNNING';
ALTER TYPE "AiAnalysisStatus" ADD VALUE IF NOT EXISTS 'FAILED';

CREATE TYPE "GeneratedTestStatus" AS ENUM ('NOT_GENERATED', 'GENERATING', 'GENERATED', 'FAILED');

ALTER TABLE "QaRun"
ADD COLUMN "generatedTestStatus" "GeneratedTestStatus" NOT NULL DEFAULT 'NOT_GENERATED';
